packages:
  - apps/*
  - packages/*

allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  "@tailwindcss/oxide": true
  bcrypt: true
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@tailwindcss/oxide"
  - bcrypt
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
