/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { accountSchema } from "../modules/accounts/dto/account.dto";
import { usersFields } from "../modules/accounts/../users/users.schema";
import { loginSchema } from "../modules/auth/dto/login.dto";
import { jwtSchema } from "../modules/auth/dto/jwt.dto";
import { carManufacturerSchema } from "../modules/car-manufacturers/dto/car-manufacturer.dto";
import { carManufacturerSortFieldQuerySchema } from "../modules/car-manufacturers/car-manufacturers.schema";
import { createPaginationSchema } from "@api/common/dto/pagination.dto";
import { limitSchema, skipSchema, sortDirectionQuerySchema } from "../modules/car-models/../../common/schemas/common.schema";
import { carManufacturerFields } from "../modules/cars/../car-manufacturers/car-manufacturers.schema";
import { carModelSchema } from "../modules/car-models/dto/car-model.dto";
import { carModelSortFieldQuerySchema } from "../modules/car-models/car-models.schema";
import { carFields, carSortByFieldQuerySchema } from "../modules/cars/cars.schema";
import { carModelFields } from "../modules/cars/../car-models/car-models.schema";
import { carResponseSchema } from "../modules/cars/dto/car.dto";
import { uuidSchema, skipLimitSchema } from "@api/common/schemas/common.schema";
import { createCarSchema } from "../modules/cars/dto/create-car.dto";
import { updateCarSchema } from "../modules/cars/dto/update-car.dto";

const appRouter = t.router({
  accounts: t.router({
    getMe: publicProcedure
      .output(accountSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateProfile: publicProcedure
      .input(z.object({
  firstName: z.string().min(1).max(100),
  lastName: z.string().min(1).max(100),
}))
      .output(accountSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    generateApiKey: publicProcedure
      .output(z
  .object({ apiKey: z.string(), hasApiKey: z.boolean() })
  .strict())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    hasApiKey: publicProcedure
      .output(z.object({ hasApiKey: z.boolean() }).strict())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getByUsername: publicProcedure
      .input(z.object({ username: usersFields.username }))
      .output(accountSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  auth: t.router({
    login: publicProcedure
      .input(loginSchema)
      .output(jwtSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    logout: publicProcedure
      .output(z.object({ success: z.boolean() }).strict())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refreshToken: publicProcedure
      .output(jwtSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  carManufacturers: t.router({
    list: publicProcedure
      .input(z
  .object({
    skip: skipSchema.optional(),
    limit: limitSchema.optional(),
    sortField: carManufacturerSortFieldQuerySchema.optional(),
    sortDirection: sortDirectionQuerySchema.optional(),
  })
  .strict()
  .optional())
      .output(createPaginationSchema(
  carManufacturerSchema,
))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  carModels: t.router({
    list: publicProcedure
      .input(z
  .object({
    manufacturerSlug: carManufacturerFields.slug.optional(),
    skip: skipSchema.optional(),
    limit: limitSchema.optional(),
    sortField: carModelSortFieldQuerySchema.optional(),
    sortDirection: sortDirectionQuerySchema.optional(),
  })
  .strict()
  .optional())
      .output(createPaginationSchema(carModelSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  cars: t.router({
    list: publicProcedure
      .input(z.object({
  modelSlug: carModelFields.slug.optional(),
  manufacturerSlug: carManufacturerFields.slug.optional(),
  color: carFields.color.optional().transform((v) => v?.toLowerCase()),
  skip: z.number().int().min(0).default(0),
  limit: z.number().int().min(0).max(100).optional().default(10),
  sortBy: carSortByFieldQuerySchema.optional(),
  sortDirection: sortDirectionQuerySchema.optional(),
}))
      .output(createPaginationSchema(carResponseSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getById: publicProcedure
      .input(z.object({ id: uuidSchema }))
      .output(carResponseSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(createCarSchema)
      .output(carResponseSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
  id: uuidSchema,
  data: updateCarSchema,
}))
      .output(carResponseSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    deleteById: publicProcedure
      .input(z.object({ id: uuidSchema }))
      .output(z.object({ success: z.boolean() }).strict())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    toggleFavorite: publicProcedure
      .input(z.object({ id: uuidSchema }))
      .output(z.object({ favorited: z.boolean() }).strict())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFavorites: publicProcedure
      .input(z
  .object({
    skip: z.number().int().min(0).default(0),
    limit: z.number().int().min(0).max(100).optional().default(10),
  })
  .optional())
      .output(createPaginationSchema(carResponseSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getMyCars: publicProcedure
      .input(skipLimitSchema)
      .output(createPaginationSchema(carResponseSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getCarsByUserId: publicProcedure
      .input(z.object({
  userId: uuidSchema,
  skip: z.number().int().min(0).default(0),
  limit: z.number().int().min(0).max(100).optional().default(10),
}))
      .output(createPaginationSchema(carResponseSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
