openapi: 3.0.0
paths:
  /v1/auth/login:
    post:
      operationId: AuthController_login_v1
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtResponseDto"
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
      tags:
        - Auth
  /v1/cars:
    post:
      operationId: CarsController_create_v1
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCarDto"
      responses:
        "201":
          description: Car created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarResponseDto"
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
      summary: Create a car
      tags: &a1
        - Cars
    get:
      operationId: CarsController_findAll_v1
      parameters:
        - name: limit
          required: false
          in: query
          description: The limit of items to be returned.
          schema:
            type: string
        - name: skip
          required: false
          in: query
          description: The amount of items to skip.
          schema:
            type: string
        - name: color
          required: false
          in: query
          description: The color of the car.
          schema:
            type: string
            maxLength: 100
        - name: model
          required: false
          in: query
          description: The model of the car.
          schema:
            type: string
            minLength: 1
            maxLength: 100
        - name: brand
          required: false
          in: query
          description: The brand of the car.
          schema:
            type: string
      responses:
        "200":
          description: List of cars
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarResponseListDto"
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
      summary: List cars
      tags: *a1
  /v1/cars/{id}:
    get:
      operationId: CarsController_findOne_v1
      parameters:
        - name: id
          required: true
          in: path
          description: id (UUID)
          schema:
            type: string
      responses:
        "200":
          description: Car successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarResponseDto"
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorResponse"
      summary: Get a car
      tags: *a1
    put:
      operationId: CarsController_update_v1
      parameters:
        - name: id
          required: true
          in: path
          description: id (UUID)
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCarDto"
      responses:
        "200":
          description: The car was successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarResponseDto"
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorResponse"
      summary: Update a car
      tags: *a1
    delete:
      operationId: CarsController_remove_v1
      parameters:
        - name: id
          required: true
          in: path
          description: id (UUID)
          schema:
            type: string
      responses:
        "204":
          description: Car deleted successfully
        "400":
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorResponse"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorResponse"
      summary: Delete a car
      tags: *a1
info:
  title: 🔥 Next Gen Nestjs API
  description: Demo API to showcase autogenerated Swagger docs from Zod schemas and tRPC.
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    BadRequestErrorItem:
      type: object
      properties:
        code:
          type: string
          example: invalid_enum_value
        path:
          example:
            - brand
          type: array
          items:
            type: string
        message:
          type: string
          example: Invalid enum value. Expected 'BMW' | 'Audi', received 'Tesla'
        received:
          type: object
          example: Tesla
          nullable: true
        options:
          example:
            - BMW
            - Audi
          nullable: true
          type: array
          items:
            type: string
      required:
        - code
        - path
        - message
        - received
        - options
    BadRequestErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
          example: 400
        errorCode:
          type: number
          example: 100
          description: Custom application error code
          enum:
            - 100
            - 101
        message:
          type: string
          example: Validation failed
        errors:
          type: array
          items:
            $ref: "#/components/schemas/BadRequestErrorItem"
      required:
        - statusCode
        - errorCode
        - message
        - errors
    LoginDto:
      type: object
      properties:
        username:
          description: The username of the user
          type: string
          minLength: 1
          maxLength: 80
        password:
          description: The password of the user
          type: string
          minLength: 5
          maxLength: 255
      required:
        - username
        - password
    JwtDto:
      type: object
      properties:
        accessToken:
          type: string
          format: jwt
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken
    JwtResponseDto:
      type: object
      properties:
        apiVersion:
          type: string
          description: The version of the API
          example: 1.0.0
        data:
          description: The data of the response
          allOf:
            - $ref: "#/components/schemas/JwtDto"
      required:
        - apiVersion
        - data
    CreateCarDto:
      type: object
      properties:
        brand:
          description: The brand of the car.
          type: string
          enum:
            - BMW
            - Mercedes
            - Porsche
            - Audi
            - Toyota
            - Honda
            - Ford
            - Tesla
            - Volkswagen
          x-nestjs_zod-parent-additional-properties: false
        model:
          description: The model of the car.
          type: string
          minLength: 1
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        year:
          description: The year the it was manufactored.
          type: integer
          minimum: 1886
          maximum: 2026
          x-nestjs_zod-parent-additional-properties: false
        color:
          description: The color of the car.
          type: string
          minLength: 0
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        kmDriven:
          type: integer
          minimum: 0
          maximum: 9007199254740991
          x-nestjs_zod-parent-additional-properties: false
        price:
          type: number
          minimum: 0
          x-nestjs_zod-parent-additional-properties: false
      required:
        - brand
        - model
        - year
        - color
        - kmDriven
        - price
    CarDto:
      type: object
      properties:
        brand:
          description: The brand of the car.
          type: string
          enum:
            - BMW
            - Mercedes
            - Porsche
            - Audi
            - Toyota
            - Honda
            - Ford
            - Tesla
            - Volkswagen
          x-nestjs_zod-parent-additional-properties: false
        model:
          description: The model of the car.
          type: string
          minLength: 1
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        year:
          description: The year the it was manufactored.
          type: integer
          minimum: 1886
          maximum: 2026
          x-nestjs_zod-parent-additional-properties: false
        color:
          description: The color of the car.
          type: string
          minLength: 0
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        kmDriven:
          type: integer
          minimum: 0
          maximum: 9007199254740991
          x-nestjs_zod-parent-additional-properties: false
        price:
          type: number
          minimum: 0
          x-nestjs_zod-parent-additional-properties: false
        id:
          description: The unique id of the car (UUID)
          type: string
          format: uuid
          pattern: ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
          x-nestjs_zod-parent-additional-properties: false
      required:
        - brand
        - model
        - year
        - color
        - kmDriven
        - price
        - id
    CarResponseDto:
      type: object
      properties:
        apiVersion:
          type: string
          description: The version of the API
          example: 1.0.0
        data:
          description: The data of the response
          allOf:
            - $ref: "#/components/schemas/CarDto"
      required:
        - apiVersion
        - data
    MetaPaginationDto:
      type: object
      properties:
        total:
          type: number
          description: The total number of items available across all pages
        limit:
          type: number
          description: The limit of items
        skipped:
          type: number
          description: Items skipped
        count:
          type: number
          description: The count of items
      required:
        - total
        - limit
        - skipped
        - count
    PaginatedItemsDto:
      type: object
      properties:
        meta:
          description: Metadata for pagination
          allOf:
            - $ref: "#/components/schemas/MetaPaginationDto"
        items:
          description: List of CarDto items
          type: array
          items:
            $ref: "#/components/schemas/CarDto"
      required:
        - meta
        - items
    CarResponseListDto:
      type: object
      properties:
        apiVersion:
          type: string
          description: The version of the API
          example: 1.0.0
        data:
          description: The data of the response
          allOf:
            - $ref: "#/components/schemas/PaginatedItemsDto"
      required:
        - apiVersion
        - data
    NotFoundErrorResponse:
      type: object
      properties:
        type:
          type: string
          example: Car
        message:
          type: string
          example: Car could not be found
      required:
        - message
    UpdateCarDto:
      type: object
      properties:
        brand:
          description: The brand of the car.
          type: string
          enum:
            - BMW
            - Mercedes
            - Porsche
            - Audi
            - Toyota
            - Honda
            - Ford
            - Tesla
            - Volkswagen
          x-nestjs_zod-parent-additional-properties: false
        model:
          description: The model of the car.
          type: string
          minLength: 1
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        year:
          description: The year the it was manufactored.
          type: integer
          minimum: 1886
          maximum: 2026
          x-nestjs_zod-parent-additional-properties: false
        color:
          description: The color of the car.
          type: string
          minLength: 0
          maxLength: 100
          x-nestjs_zod-parent-additional-properties: false
        kmDriven:
          type: integer
          minimum: 0
          maximum: 9007199254740991
          x-nestjs_zod-parent-additional-properties: false
        price:
          type: number
          minimum: 0
          x-nestjs_zod-parent-additional-properties: false
